<?php

	// include Facebook and Facebook Ads library
	$fb_path = function_exists('libraries_get_path') ? libraries_get_path('facebook-php-sdk') : '/var/www/vhosts/boucado.space/httpdocs/sites/all/libraries/facebook-php-sdk';
	$fb_ads_path = function_exists('libraries_get_path') ? libraries_get_path('facebook-php-ads-sdk') : '/var/www/vhosts/boucado.space/httpdocs/sites/all/libraries/facebook-php-ads-sdk';

	require_once $fb_path . '/vendor/autoload.php';  
	require_once $fb_ads_path . '/vendor/autoload.php';

	// Add to header of your file
	use Facebook\Facebook;
	use Facebook\Exceptions\FacebookResponseException;
	use Facebook\Exceptions\FacebookSDKException;
	
	use FacebookAds\Api;
	
	use FacebookAds\Object\AdUser;
	use FacebookAds\Object\Fields\AdUserFields;
	use FacebookAds\Object\AdAccount;
	use FacebookAds\Object\Fields\AdAccountFields;	


function fbads_print_pre($p,$titel="") {
	if ($titel<>"") {print $titel . ": ";} 
	print "<pre>";
	print_r($p);
	print "</pre>";
}

function fbads_init() {
    drupal_add_css(drupal_get_path('module', 'fbads') . '/fbads.css');
	
	fbads_get_access_token();
	
	// Initialize a new Session and instantiate an Api object
	Api::init(
	  variable_get('fbads_app_id'), // App ID
	  variable_get('fbads_app_secret'),
	  $_SESSION['facebook_access_token'] // Your user access token
	  //variable_get('fbads_access_token')
	);
	
	
}

function fbads_permission() {
  return array(
    'access fbads' => array(
      'title' => t('Access Facebook Ads'),
    ),
  );
}

function fbads_menu() {
    $items = array();
	
	    $items['admin/config/services/fbads'] = array(
        'title' => t('Facebook Ads'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('fbads_admin_config_form'),  
        'access arguments' => array('administer site configuration'),
        'type' => MENU_CALLBACK,
    );
	
    $items['fbads/tests'] = array(
        'title' => t('Tests'),
        'access arguments' => array('administer site configuration'),
        'page arguments' => array(0),  
        'page callback' => 'fbads_tests',
    );
	
	return $items;
}

function fbads_tests(){
		
	$me = new AdUser('me');

	//$my_adaccount = $me->getAdAccounts()->current();
	//fbads_print_pre($my_adaccount->getData());
	
	$my_adaccount = $me->getAdAccounts([variable_get('fbads_ad_account')]);
	fbads_print_pre($my_adaccount->getData());

	return "test";
}

function fbads_admin_config_form($form,&$form_state){
			
		$form['app_id'] = array(
		'#type' => 'textfield',
		'#title' => t('App ID'),
		'#default_value' => variable_get('fbads_app_id'),
		'#required' => TRUE
		);
		
		$form['app_secret'] = array(
		'#type' => 'textfield',
		'#title' => t('App Secret'),
		'#default_value' => variable_get('fbads_app_secret'),
		'#required' => TRUE
		);

		$form['ad_account'] = array(
		'#type' => 'textfield',
		'#title' => t('Ad Account'),
		'#default_value' => variable_get('fbads_ad_account'),		
		'#required' => TRUE
		);
		
		$form['access_token'] = array(
		'#type' => 'textarea',
		'#title' => t('Access Token'),
		'#default_value' => variable_get('fbads_access_token'),		
		'#required' => TRUE
		);
	
		
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);		
	
	return $form;
}

function fbads_admin_config_form_submit(&$form_state) {
	variable_set('fbads_app_id', $form_state['app_id']['#value']);
	variable_set('fbads_app_secret', $form_state['app_secret']['#value']);	
	variable_set('fbads_access_token', $form_state['access_token']['#value']);
	variable_set('fbads_ad_account', $form_state['ad_account']['#value']);
	
	drupal_set_message(t('Your configuration has been saved.'));
}


function fbads_get_access_token(){

	$fb = new Facebook([
	  'app_id' => variable_get('fbads_app_id'),
	  'app_secret' => variable_get('fbads_app_secret'),]
	);
	
	$helper = $fb->getRedirectLoginHelper();
	
	if (!isset($_SESSION['facebook_access_token'])) {
	  $_SESSION['facebook_access_token'] = null;
	}
	
	if (!$_SESSION['facebook_access_token']) {
	  $helper = $fb->getRedirectLoginHelper();
	  try {
	    $_SESSION['facebook_access_token'] = (string) $helper->getAccessToken();
	  } catch(FacebookResponseException $e) {
	    // When Graph returns an error
	    drupal_set_message('Graph returned an error: ' . $e->getMessage(), 'error');
	    return;
	  } catch(FacebookSDKException $e) {
	    // When validation fails or other local issues
	    drupal_set_message( 'Facebook SDK returned an error: ' . $e->getMessage(), 'error');
	    return;
	  }
	}
	
	if (!$_SESSION['facebook_access_token']) {
	  $permissions = ['ads_management'];
	  $loginUrl = $helper->getLoginUrl('http://www.boucado.space/', $permissions);
	  echo '<a href="' . $loginUrl . '">Log in with Facebook</a>';
	} 

}


